apiVersion: v1

kind: Service

metadata:
  name: rca-api-service

spec:

  selector:
    app: rca-api

  ports:

  - protocol: TCP

    port: 80

    targetPort: 8000

  type: LoadBalancer